name: CI

on:
  push:
    branches:
      - main
      - master
      - develop
      - "feature/**"
  pull_request:

jobs:
  lint-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - name: Installer les dépendances
        run: pnpm install --frozen-lockfile

      - name: Générer Prisma Client
        run: pnpm prisma generate

      - name: Lint
        run: pnpm lint

      - name: Build
        run: pnpm build